language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
matrix:
 allow_failures:
 - julia: nightly
branches:
  except:
  - development
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Microeconometrics")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'using Pkg; cd(Pkg.dir("Microeconometrics")); ps=Pkg.PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps); include(joinpath("docs", "make.jl"))'
